### ISSUE TITLE
Understanding difference in inner product

### ISSUE THREAD

**Issue by davibarreira** [Jollywatt/GeometricAlgebra.jl#2]
Hey, thanks for this package. I've been playing around with geometric algebra for a while, and I'm always trying out the different packages available. I was trying to test your package for discrete differential geometry, and I'm getting results a bit different when compared to other implementations.

Using your package, the following inner product returns 40:
```julia
using GeometricAlgebra
@basis 3
u = 2*v1 + 2*v2
v = -2*v1 + 2*v2
a = v1 + 3*v2
b = 2*v1 + v2
inner(a∧b,u∧v) == 40
```

In Grassmann.jl, the same operation returns -40 (which is actually the "correct" result in my reference):
```julia
using Grassmann
@basis ℝ^3 E e
u = 2*e1 + 2*e2
v = -2*e1 + 2*e2
a = e1 + 3*e2
b = 2*e1 + e2
(a∧b) | (u∧v) == -40
```

I also get 40 using CliffordAlgebras.jl. I was wondering why was that? I mean, is Grassmann.jl and GeometricAlgebras.jl using different signatures somehow? 

Thanks!

**Comment by chakravala** [comment]
Most geometric algebra developers dont have a clue about what the
definitions should be, that's why using these other packages leads to
errors with the minus sign. I have thoroughly studied this phenomenon and
pointed it out many times. These imitation package developers do not have
the depth of knowledge I have, so they make mistakes. Even the authors of
many papers including Hestenes use wrong definitions, because they did not
study thoroughly enough.

**Comment by chakravala** [comment]
Also, on addition I'd like to mention that I have already published an
entire discrete exterior calculus framework for Grassmann.jl, I only have
not documented it yet, because all these imitation packages annoy me.

If you are very serious about working on this and dont plan to make another
mediocre imitation of my work, I can show you, but you know how academia
is, it's all backstabbing and sociopathy.

**Comment by davibarreira** [comment]
I don't plan on developing any packages related to it. I'm studying Discrete Differential Geometry following the lectures of professor Keenan Crane, and I was trying to code along. Grassmann.jl seems super advanced, and my mathematical knowledge stumbles when I try to understand the docs.

**Comment by chakravala** [comment]
The Grassmann.jl docs are more of a puzzle to be honest, I am interested in
making better documentation, but it's not the most important thing when
nobody wants to actually collaborate and properly credit my work.

This isn't my repository, so I'm not gonna say a lot more here, but
essentially JollyWatt probably thought its best to use a Hestenes style
definition, even though Hestenes was incorrect and leads to
inconsistencies. Unfortunately, Hestenes did not properly study pure
Grassmann algebra, and so he lacked some of the insight needed to make the
correct definitions in his papers. As a consequence, you get people like
JollyWatt making mistakes.

**Comment by Jollywatt** [comment]
@davibarreira Thanks for the question. The reason is one of differing convention, unfortunately. In GeometricAlgebra.jl, the ‘inner product’ is defined as

```math
A ⋅ B ≔ \sum_{p,q} ⟨⟨A⟩_p ⟨B⟩_q⟩_{|p - q|} \tag{1}
```

as in [the docs](https://jollywatt.github.io/GeometricAlgebra.jl/dev/theory/products/#Generalised-inner-product), following the conventions of Leo Dorst and others ([see here for a good reference](https://www.researchgate.net/profile/Leo-Dorst/publication/2842332_The_Inner_Products_of_Geometric_Algebra/links/0fcfd510ccb2727f7a000000/The-Inner-Products-of-Geometric-Algebra.pdf)).

This definition is chosen for its similarity with the other definitions of the generalized wedge product and left and right contractions (for them, simply replace $|p - q|$ with $p + q$ or $p - q$, etc.) However, as you pointed out, there are other well-motivated definitions for the inner product, such as the one Grassmann.jl and CliffordAlgebras.jl use. I believe they use a definition chosen so that the identity
```math
e_I ⋅ e_J = \begin{cases} 1 & \text{if $I = J$} \\ 0 & \text{if $I \ne J$} \end{cases} \tag{2}
```
holds for an orthonormal basis $\{e_i\}$ where $I$ and $J$ are multi-indices. This is certainly a nice property for your inner product to have, and is what is usually meant by the [induced inner product on $k$-forms](https://en.wikipedia.org/wiki/Hodge_star_operator ) from exterior calculus.

Both definitions have their advantages (and it goes without saying, but neither definition is “wrong” — they are definitions) and the two are related by reversion of the second argument: $A ⋅ B = A \hat⋅\tilde{B}$.

I believe I chose the first convention for this package because of its agreement with the other “graded products”, and because the nice property $(2)$ can also be served by the use of a “reciprocal basis” $e^I$ such that $e_I e^J = \delta_I^J$, which is commonly done.

*Edit:* If you want to define an inner product that agrees with Grassmann, try
```julia
inner2(a, b) = inner(a, ~b)
```

**Comment by davibarreira** [comment]
Thanks for the clarifications.

**Comment by chakravala** [comment]
Also, note that Grassmann.jl also allows you to use the "Dorst" style
interior product, they are << and >> instead of < and > ... so Grassmann.jl
certainly allows you to use incorrect definitions, but they are incorrect.
I do not prevent people from repeating the mistakes of others, even though
I severely disagree.
